"""
Executes SQL statements from MCP DDL plan using Databricks Managed MCP endpoint.

Expected input plan format: mcp_plan.json generated by mcp_excel_sql_planner.py
"""

import argparse
import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests


def resolve_mcp_url() -> str:
    explicit_url = os.environ.get("DATABRICKS_MCP_URL", "").strip()
    if explicit_url:
        return explicit_url.rstrip("/")

    host = os.environ.get("DATABRICKS_HOST", "").strip().rstrip("/")
    if not host:
        raise ValueError("Missing DATABRICKS_MCP_URL (or DATABRICKS_HOST fallback)")

    if not host.startswith("http://") and not host.startswith("https://"):
        host = f"https://{host}"

    return f"{host}/api/2.0/mcp/sql"


def resolve_token() -> str:
    token = (
        os.environ.get("COPILOT_MCP_DATABRICKS_TOKEN", "").strip()
        or os.environ.get("DATABRICKS_TOKEN", "").strip()
    )
    if not token:
        raise ValueError("Missing COPILOT_MCP_DATABRICKS_TOKEN (or DATABRICKS_TOKEN fallback)")
    return token


def call_mcp_tool(mcp_url: str, token: str, tool_name: str, statement: str, request_id: int) -> Dict[str, Any]:
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    candidate_arguments = [
        {"statement": statement},
        {"sql": statement},
        {"query": statement},
    ]

    last_error: Optional[str] = None

    for arguments in candidate_arguments:
        payload = {
            "jsonrpc": "2.0",
            "id": request_id,
            "method": "tools/call",
            "params": {
                "name": tool_name,
                "arguments": arguments,
            },
        }

        response = requests.post(mcp_url, headers=headers, json=payload, timeout=120)

        if response.status_code >= 400:
            last_error = f"HTTP {response.status_code}: {response.text[:1000]}"
            continue

        data = response.json()
        if data.get("error"):
            last_error = json.dumps(data.get("error"))
            continue

        return {"success": True, "response": data, "used_arguments": arguments}

    return {"success": False, "error": last_error or "Unknown MCP error"}


def execute_plan(plan: List[Dict[str, Any]], mcp_url: str, token: str, tool_name: str) -> List[Dict[str, Any]]:
    results: List[Dict[str, Any]] = []

    request_id = 1
    for item in plan:
        if not item.get("valid"):
            results.append(
                {
                    "table": item.get("table", ""),
                    "column": item.get("column", ""),
                    "datatype": item.get("datatype", ""),
                    "status": "FAILED",
                    "error": item.get("error", "Invalid plan row"),
                    "alter_result": None,
                    "update_result": None,
                }
            )
            continue

        alter_sql = item.get("alter_sql", "")
        update_sql = item.get("update_sql")

        alter_call = call_mcp_tool(mcp_url, token, tool_name, alter_sql, request_id)
        request_id += 1

        if not alter_call.get("success"):
            results.append(
                {
                    "table": item.get("table", ""),
                    "column": item.get("column", ""),
                    "datatype": item.get("datatype", ""),
                    "status": "FAILED",
                    "error": f"ALTER failed: {alter_call.get('error')}",
                    "alter_result": alter_call,
                    "update_result": None,
                }
            )
            continue

        update_call = None
        if update_sql:
            update_call = call_mcp_tool(mcp_url, token, tool_name, update_sql, request_id)
            request_id += 1
            if not update_call.get("success"):
                results.append(
                    {
                        "table": item.get("table", ""),
                        "column": item.get("column", ""),
                        "datatype": item.get("datatype", ""),
                        "status": "PARTIAL",
                        "error": f"Column added but UPDATE failed: {update_call.get('error')}",
                        "alter_result": alter_call,
                        "update_result": update_call,
                    }
                )
                continue

        results.append(
            {
                "table": item.get("table", ""),
                "column": item.get("column", ""),
                "datatype": item.get("datatype", ""),
                "status": "SUCCESS",
                "error": None,
                "alter_result": alter_call,
                "update_result": update_call,
            }
        )

    return results


def build_report(results: List[Dict[str, Any]]) -> str:
    total_count = len(results)
    success_count = sum(1 for row in results if row.get("status") == "SUCCESS")
    partial_count = sum(1 for row in results if row.get("status") == "PARTIAL")
    failed_count = total_count - success_count - partial_count

    if total_count > 0 and failed_count == 0 and partial_count == 0:
        status_title = "## ✅ MCP Databricks Execution Successful"
        overall_status = "SUCCESS"
    elif success_count > 0 or partial_count > 0:
        status_title = "## ⚠️ MCP Databricks Execution Completed with Issues"
        overall_status = "PARTIAL"
    else:
        status_title = "## ❌ MCP Databricks Execution Failed"
        overall_status = "FAILED"

    lines: List[str] = [status_title, ""]
    lines.append("**Summary:**")
    lines.append(f"- Overall status: {overall_status}")
    lines.append(f"- Total operations: {total_count}")
    lines.append(f"- ✅ Successful: {success_count}")
    lines.append(f"- ⚠️ Partial: {partial_count}")
    lines.append(f"- ❌ Failed: {failed_count}")
    lines.append("")

    if partial_count > 0:
        lines.append("### ⚠️ Partial Operations")
        lines.append("| Table | Column | Issue |")
        lines.append("|---|---|---|")
        for row in results:
            if row.get("status") == "PARTIAL":
                lines.append(f"| {row.get('table', '')} | {row.get('column', '')} | {row.get('error', 'Unknown')} |")
        lines.append("")

    if failed_count > 0:
        lines.append("### ❌ Failed Operations")
        lines.append("| Table | Column | Error |")
        lines.append("|---|---|---|")
        for row in results:
            if row.get("status") == "FAILED":
                lines.append(f"| {row.get('table', '')} | {row.get('column', '')} | {row.get('error', 'Unknown')} |")
        lines.append("")

    if success_count > 0:
        lines.append("### ✅ Successful Operations")
        lines.append("| Table | Column | Datatype |")
        lines.append("|---|---|---|")
        for row in results:
            if row.get("status") == "SUCCESS":
                lines.append(
                    f"| {row.get('table', '')} | {row.get('column', '')} | {row.get('datatype', '')} |"
                )
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Execute MCP SQL plan")
    parser.add_argument("--plan", default="mcp_plan.json", help="Path to plan JSON file")
    parser.add_argument("--report", default="mcp_execution_report.md", help="Output markdown report")
    parser.add_argument("--tool", default="databricks_sql_execute", help="MCP tool name for SQL execution")
    args = parser.parse_args()

    plan_path = Path(args.plan)
    if not plan_path.exists():
        raise FileNotFoundError(f"Plan file not found: {plan_path}")

    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    if not isinstance(plan, list):
        raise ValueError("Invalid plan format: expected JSON array")

    mcp_url = resolve_mcp_url()
    token = resolve_token()

    results = execute_plan(plan, mcp_url, token, args.tool)
    report = build_report(results)

    Path(args.report).write_text(report, encoding="utf-8")

    print("MCP execution completed")
    print(f"Report file: {args.report}")


if __name__ == "__main__":
    main()
